### ISSUE TITLE
Scenario's voor ketentesten leverancier (Epic)

### ISSUE THREAD

**Issue by w-van-weelden** [VNG-Realisatie/api-test-platform#346]
Als leverancier van consumers, wil ik scenario's testen in het API Testplatform vanuit onze ontwikkelomgevingen zodat we een compliancyrapport kunnen maken om aan te tonen dat de API's correct worden ondersteund vanuit een applicatie.
...zodat [vul aan].

**Toelichting**:
Een belangrijk instrument om de kwaliteit van StUF-implementaties te waarborgen, is het StUF-testplatform. Wanneer verschillende partijen ‘groene vinkjes’ hebben op het testplatform, toont dat aan dat de basis op orde is. Bij het aansluiten van verschillende systemen, zal de basis-koppeling dan werken. In het StUF-testplatform moet een applicatie scenario's doorlopen waarin wordt gecontroleerd of de basisfunctionaliteiten correct werken.

Als leverancier willen we dit soort scenario's kunnen doorlopen en (als vervolg) compliancy rapporten voor een applicatie genereren zodat we kunnen bewijzen dat implementaties voldoen aan de standaard. Dit is bijvoorbeeld bij aanbestedingen nodig als een bewijs van compliancy wordt gevraagd. Ook helpt het gemeenten om te kunnen vertrouwen op de juiste implementatie bij de oplossingen die zij gebruiken.

Het is hierbij noodzakelijk dat er een administratie is van aangesloten systemen, zodat voor elk systeem apart een test kan worden uitgevoerd en op een later moment een compliancyrapport kan worden gemaakt.

**Oplossingsrichting**:
 - Definiëren van de scenario's: hiervoor kunnen we de scenario's van het StUF-testplatform hergebruiken
 - Inbouwen van scenario's in api-test.nl

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] Duidelijke definities en specificatie van scenario's, bijbehorende berichten en datasets
- [ ] Ondersteuning voor controles in het api-platform
- [ ] Ondersteuning in API-Platform om berichten te relateren aan applicaties
- [ ] Inhoudelijke foutmeldingen voor fouten in berichtopbouw en berichtinhoud om leveranciers te helpen bij implementatie

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Dank voor het indienen van deze issue, in principe zit de voorgestelde functionaliteit in api-test.nl als Consumer tests ( voorbeeld voor ZGW: https://api-test.nl/consumer/1/ ) echter de consumer-scenario's vanuit het StUF-testplatform zijn inderdaad nog niet overgezet en de huidige set van scenario's is weinig representatief.

@michielverhoef wellicht dat het handig is om dit met Henri te bespreken aangezien dit onder zijn hoede is gerealiseerd maar de aandacht is vooral naar provider-compliancy gegaan.
